name: Comprueba iv.yaml
on:
  pull_request:
    paths:
      - "**/*.yml"
      - "**/*.yaml"

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Baja fuentes
      - name: Comprueba YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: iv.yaml

